"""Create table Orders

Revision ID: c0587edc3bb7
Revises: 
Create Date: 2026-01-16 19:38:01.043194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0587edc3bb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_number', sa.String(length=255), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('customer_price', sa.Float(), nullable=False),
    sa.Column('total_discount_percent', sa.Float(), nullable=False),
    sa.Column('total_discount_value', sa.Float(), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shipment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_date_begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_lines_order', 'orders', ['posting_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_lines_order', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
