"""Add column name into teble Orders

Revision ID: fb20ae706259
Revises: c0587edc3bb7
Create Date: 2026-01-16 22:04:18.341412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb20ae706259'
down_revision: Union[str, Sequence[str], None] = 'c0587edc3bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
