"""Separate Order and OrderItems

Revision ID: be455eb3b042
Revises: 6c530ec89219
Create Date: 2026-02-08 15:27:13.110768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be455eb3b042'
down_revision: Union[str, Sequence[str], None] = '6c530ec89219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(
        'uq_orders_posting_number',  # имя constraint
        'orders',
        ['posting_number']
    )


    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_posting_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_cancelled', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('payout', sa.NUMERIC(), nullable=False),
    sa.Column('price', sa.NUMERIC(), nullable=False),
    sa.Column('customer_price', sa.NUMERIC(), nullable=False),
    sa.Column('total_discount_percent', sa.Float(), nullable=False),
    sa.Column('total_discount_value', sa.Float(), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.BigInteger(), nullable=False),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.Column('is_returned_finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_posting_number'], ['orders.posting_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_posting_number'), 'order_items', ['order_posting_number'], unique=False)
    op.create_index(op.f('ix_order_items_sku'), 'order_items', ['sku'], unique=True)
    op.drop_index(op.f('ix_order_lines_order'), table_name='orders')
    op.create_index(op.f('ix_orders_shipment_date'), 'orders', ['shipment_date'], unique=False)
    op.drop_column('orders', 'is_returned')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'commission_percent')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'offer_id')
    op.drop_column('orders', 'payout')
    op.drop_column('orders', 'commission_amount')
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'id')
    op.drop_column('orders', 'total_discount_value')
    op.drop_column('orders', 'sku')
    op.drop_column('orders', 'total_discount_percent')
    op.drop_column('orders', 'customer_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total_discount_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('sku', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total_discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('orders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('commission_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('payout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('offer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('commission_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('is_returned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_orders_shipment_date'), table_name='orders')
    op.create_index(op.f('ix_order_lines_order'), 'orders', ['posting_number'], unique=False)
    op.drop_index(op.f('ix_order_items_sku'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_posting_number'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_constraint('uq_orders_posting_number', 'orders', type_='unique')
    # ### end Alembic commands ###
